apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: tenant-db-secret
  namespace: acme-corp

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore

  target:
    name: tenant-db-secret

  data:
  - secretKey: credentials
    remoteRef:
      key: tenant-acme-corp-credentials