apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: tenant-secret-reader
  namespace: acme-corp

rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["tenant-acme-corp-secret"]
  verbs: ["get"]